In [27]:
from pathlib import Path
import pandas as pd
import numpy as np
import plotly.express as px
from plotly.subplots import make_subplots

name_mapping = {
    'control': 'Control (Retrain)',
    'certified_deep_unlearning': 'Certified Deep Unlearning',
    'amnesiac': 'Amnesiac',
    'bad_teacher': 'Bad Teacher',
    'ssd': "SSD",
    'grad_ascent': 'Gradient Ascent',
    'scrub': 'SCRUB',
    'swap_test_score': 'SWAP Test'
}

In [28]:
distinguisher_to_plot = 'kld'
# poison_type = 'badnets'
# experiment_dir = Path(f'/home/unlearning/mirror-mirror/output/{poison_type}_poison_cifar10_resnet18_32_trials')
# experiment_dir = Path('/home/unlearning/mirror-mirror/gaussian_poison_32_trials')
experiment_dir = Path('/home/unlearning/mirror-mirror/output/swap_gaussian_32_trials')

In [29]:
distinguisher_dfs = []

# Get the distinguisher data
for p in experiment_dir.iterdir():
    if p.name.endswith('csv'):
        distinguisher_name = '_'.join(p.stem.split('_')[0:-1])
        distinguisher_df = pd.read_csv(str(p))
        if 'accuracy' not in p.stem.split('_') and 'tpr' not in p.stem.split('_'):
            distinguisher_df['distinguisher'] = [distinguisher_name] * len(distinguisher_df.index)
            distinguisher_df['poison_rate'] = distinguisher_df['forget_set'].apply(lambda x: float(x.split('_')[1]))
            distinguisher_dfs.append(distinguisher_df)

# Add in performance figures
for df in distinguisher_dfs:
    clean_acc_df = pd.read_csv(str(experiment_dir / 'clean_accuracy_results.csv'))
    poison_acc_df = pd.read_csv(str(experiment_dir / 'poison_accuracy_results.csv'))
    df['clean_accuracy'] = clean_acc_df['score']#.apply(lambda x: x * 100)
    df['poison_accuracy'] = poison_acc_df['score']#.apply(lambda x: x * 100)

data_df = pd.concat(distinguisher_dfs, axis=0)
data_df['model'] = data_df['model'].apply(lambda x: name_mapping[x])
# data_df = data_df[data_df['poison_rate'] == 0.1]
data_df.head()

,forget_set,run_number,model,score,distinguisher,poison_rate,clean_accuracy,poison_accuracy
0,poison_0.1,0,Control (Retrain),9.436810,kld,0.1,0.8220,0.0910
1,poison_0.1,0,Amnesiac,7.136070,kld,0.1,0.7946,0.0002
2,poison_0.1,0,Bad Teacher,2.716671,kld,0.1,0.8102,0.0208
3,poison_0.1,0,Gradient Ascent,1680.907227,kld,0.1,0.1338,0.0000
4,poison_0.1,0,SCRUB,669.996277,kld,0.1,0.2380,0.0000

In [30]:
diffs_dfs = []
control_scores = data_df[data_df['model'] == 'Control (Retrain)'].reset_index(drop=True)['score']
for c in data_df['model'].unique():
    if 'Control' not in c:
        curr_df = data_df[data_df['model'] == c].reset_index(drop=True)
        curr_scores = curr_df['score']
        curr_diffs = np.abs(curr_scores - control_scores)
        curr_df['control_score_diffs'] = curr_diffs
        diffs_dfs.append(curr_df)
diffs_df = pd.concat(diffs_dfs)
diffs_df.head()

,forget_set,run_number,model,score,distinguisher,poison_rate,clean_accuracy,poison_accuracy,control_score_diffs
0,poison_0.1,0,Amnesiac,7.136070,kld,0.1,0.7946,0.0002,2.300740
1,poison_0.1,1,Amnesiac,7.341456,kld,0.1,0.8102,0.0002,2.246650
2,poison_0.1,2,Amnesiac,7.355752,kld,0.1,0.7860,0.0006,2.269756
3,poison_0.1,0,Amnesiac,1.000000,mia,0.1,0.7946,0.0002,0.339600
4,poison_0.1,1,Amnesiac,1.000000,mia,0.1,0.8102,0.0002,0.316200

In [31]:
data_df[data_df['model'] == 'Control (Retrain)']

,forget_set,run_number,model,score,distinguisher,poison_rate,clean_accuracy,poison_accuracy
0,poison_0.1,0,Control (Retrain),9.436810,kld,0.1,0.8220,0.0910
6,poison_0.1,1,Control (Retrain),9.588106,kld,0.1,0.8318,0.0840
12,poison_0.1,2,Control (Retrain),9.625507,kld,0.1,0.8304,0.0852
0,poison_0.1,0,Control (Retrain),0.660400,mia,0.1,0.8220,0.0910
6,poison_0.1,1,Control (Retrain),0.683800,mia,0.1,0.8318,0.0840
12,poison_0.1,2,Control (Retrain),0.695800,mia,0.1,0.8304,0.0852
0,poison_0.1,0,Control (Retrain),0.122298,mse,0.1,0.8220,0.0910
6,poison_0.1,1,Control (Retrain),0.121539,mse,0.1,0.8318,0.0840
12,poison_0.1,2,Control (Retrain),0.122280,mse,0.1,0.8304,0.0852

In [32]:
diffs_plot_df = diffs_df.drop(['forget_set'], axis=1)
diffs_plot_df = diffs_plot_df.groupby(['poison_rate', 'distinguisher', 'model']).agg(
    mean_score_diff=('control_score_diffs', 'mean'),
    std_score_diff=('control_score_diffs', 'std'),
    mean_poison_accuracy=('poison_accuracy', 'mean'),
    std_poison_accuracy=('poison_accuracy', 'std'),
    mean_clean_accuracy=('clean_accuracy', 'mean'),
    std_clean_accuracy=('clean_accuracy', 'std')
).reset_index()
diffs_plot_df.head()

,poison_rate,distinguisher,model,mean_score_diff,std_score_diff,mean_poison_accuracy,std_poison_accuracy,mean_clean_accuracy,std_clean_accuracy
0,0.1,kld,Amnesiac,2.272382,0.027141,0.000333,0.000231,0.796933,0.012268
1,0.1,kld,Bad Teacher,6.753546,0.043036,0.007133,0.011836,0.810067,0.004002
2,0.1,kld,Gradient Ascent,1656.180205,47.233310,0.000000,0.000000,0.143000,0.037262
3,0.1,kld,SCRUB,691.019785,112.100958,0.000000,0.000000,0.234733,0.005486
4,0.1,kld,SSD,9.550141,0.099913,0.999733,0.000462,0.831067,0.003754

In [33]:
data_df[data_df['distinguisher'] == 'swap_test_score']

,forget_set,run_number,model,score,distinguisher,poison_rate,clean_accuracy,poison_accuracy
0,poison_0.1,0,Amnesiac,0.9889,swap_test_score,0.1,0.8220,0.0910
1,poison_0.1,0,Bad Teacher,0.9998,swap_test_score,0.1,0.7946,0.0002
2,poison_0.1,0,Gradient Ascent,1.0000,swap_test_score,0.1,0.8102,0.0208
3,poison_0.1,0,SCRUB,0.9921,swap_test_score,0.1,0.1338,0.0000
4,poison_0.1,0,SSD,0.9981,swap_test_score,0.1,0.2380,0.0000
5,poison_0.1,1,Amnesiac,0.9778,swap_test_score,0.1,0.8290,1.0000
6,poison_0.1,1,Bad Teacher,0.9962,swap_test_score,0.1,0.8318,0.0840
7,poison_0.1,1,Gradient Ascent,0.9996,swap_test_score,0.1,0.8102,0.0002
8,poison_0.1,1,SCRUB,0.9789,swap_test_score,0.1,0.8140,0.0002
9,poison_0.1,1,SSD,0.9980,swap_test_score,0.1,0.1840,0.0000
10,poison_0.1,2,Amnesiac,0.9694,swap_test_score,0.1,0.2378,0.0000
11,poison_0.1,2,Bad Teacher,0.9987,swap_test_score,0.1,0.8354,0.9992
12,poison_0.1,2,Gradient Ascent,1.0000,swap_test_score,0.1,0.8304,0.0852
13,poison_0.1,2,SCRUB,0.9907,swap_test_score,0.1,0.7860,0.0006
14,poison_0.1,2,SSD,0.9977,swap_test_score,0.1,0.8060,0.0004

In [34]:
px.scatter(
    data_df[data_df['poison_rate'] == 0.1],
    x='clean_accuracy',
    y='poison_accuracy',
    color='model',
    # size='poison_rate'
)

In [17]:
px.scatter(
    data_df[data_df['distinguisher'] == 'kld'],
    x='score',
    y='poison_accuracy',
    color='model',
    size='poison_rate'
)

In [21]:
control_performance = data_df[data_df['model'] == 'Control (Retrain)'].reset_index(drop=True)['poison_accuracy']

# fig = px.scatter(
#     diffs_df[(diffs_df['distinguisher'] == 'mia')],
#     x='control_score_diffs',
#     y='poison_accuracy',
#     color='model',
#     labels={
#         'model': 'Unlearning Method',
#         'control_score_diffs': "Absolute Difference in KLD Scores",
#         'poison_accuracy': "Poison Accuracy"
#     },
#     category_orders={'model': ['Amnesiac', 'Bad Teacher', 'SSD']},
#     trendline="ols",
#     trendline_scope="overall",
#     trendline_color_override="black"
# )
# fig.update_xaxes(title_text="Absolute Difference between MIA scores of Control and Unlearned Models", row=1, col=1)
# fig.update_yaxes(title_text="Poison Accuracy", row=1, col=1)

fig = px.scatter(
    diffs_df[diffs_df['distinguisher'] == 'kld'],
    x='control_score_diffs',
    y='poison_accuracy',
    color='model',
    labels={
        'model': 'Unlearning Method',
        'control_score_diffs': "Absolute Difference in KLDScores",
        'poison_accuracy': "Poison Accuracy"
    },
    category_orders={'model': ['Amnesiac', 'Bad Teacher', 'SSD']},
    trendline="ols",
    trendline_scope="overall",
    trendline_color_override="black"
)
fig.update_xaxes(title_text="Absolute Difference between KLDScores of Control and Unlearned Models")
fig.update_yaxes(title_text="Poison Accuracy")

# Add line for control performance
# fig.add_hline(
#     y=control_performance.mean(), 
#     opacity=1, 
#     line_width=3, 
#     line_dash='dash', 
#     line_color='Black', 
#     annotation_text=f'Control Performance: {control_performance.mean():.3f}', 
#     annotation_position='top left', 
#     annotation_font_size=14
# )

fig.show(renderer='png', width=1700, height=500)

RuntimeError:

Kaleido requires Google Chrome to be installed.

Either download and install Chrome yourself following Google's instructions for your operating system,
or install it from your terminal by running:

    $ plotly_get_chrome

In [ ]:
results = px.get_trendline_results(fig).iloc[0]['px_fit_results']
print(results.summary())

In [ ]:
results.tvalues

In [35]:
exp_dir = Path(experiment_dir)
distinguishers = [fp for fp in exp_dir.iterdir() if str(fp).endswith('csv') and fp.stem[:-len('_results')] not in ['clean_accuracy', 'poison_accuracy', 'poison_tpr', 'swap_test_score']]
poison_acc_df = pd.read_csv(str(experiment_dir / 'poison_accuracy_results.csv'))
clean_acc_df = pd.read_csv(str(experiment_dir / 'clean_accuracy_results.csv'))
poison_tpr_df = pd.read_csv(str(experiment_dir / 'poison_tpr_results.csv'))
swap_test_df = pd.read_csv(str(experiment_dir / 'swap_test_score_results.csv'))

graph_data = []
all_means = []
adv_data = []
for distinguisher_fp in distinguishers:
    distinguisher_data = pd.read_csv(distinguisher_fp)
    # unlearning_approaches = distinguisher_data['model'].unique()
    # for ul_approach in unlearning_approaches:
    for forget_set_size in distinguisher_data['forget_set'].unique():
        control_data = distinguisher_data[np.array(distinguisher_data['model'] == 'control') & np.array(distinguisher_data['forget_set'] == forget_set_size)]
        for ul_approach in distinguisher_data['model'].unique():
            ul_string = name_mapping[ul_approach]
            condition = np.array(distinguisher_data['forget_set'] == forget_set_size) & np.array(distinguisher_data['model'] == ul_approach)
            ul_data = distinguisher_data[condition]
            clean_acc_data = clean_acc_df[condition]
            poison_acc_data = poison_acc_df[condition]
            poison_tpr_data = poison_tpr_df[condition]
            
            graph_data.append({
                'score': ul_data['score'].mean(),
                'model': ul_string,
                'forget_set_size': forget_set_size.split('_')[-1],
                'std': ul_data['score'].std(),
            })
            if ul_approach != 'control':
                swap_test_data = swap_test_df[np.array(swap_test_df['forget_set'] == forget_set_size) & np.array(swap_test_df['model'] == ul_approach)]
                greater_than = (ul_data['score'].values > control_data['score'].values).sum() / len(ul_data['score'].values)
                less_than = (ul_data['score'].values < control_data['score'].values).sum() / len(ul_data['score'].values)
                equal_to = (ul_data['score'].values == control_data['score'].values).sum() / len(ul_data['score'].values)

                win_percentage =  max(greater_than, less_than) + (equal_to / 2)
                advantage = (win_percentage - 0.5) * 2
                row_data = {
                    'distinguisher': distinguisher_fp.stem[:-len('_results')],
                    'advantage': advantage,
                    'forget_set_size': forget_set_size.split('_')[-1],
                    'win_percentage': win_percentage,
                    'model': ul_string,
                    'clean_accuracy': clean_acc_data['score'].mean(),
                    'poison_accuracy': poison_acc_data['score'].mean(),
                    'poison_tpr': poison_tpr_data['score'].mean(),
                    'swap_test_score': swap_test_data['score'].mean()
                }
                adv_data.append(row_data)
            
        # ul_approach == distinguisher_data['model']
        # if ul_approach == 'control':
        #     ul_data = distinguisher_data[distinguisher_data['forget_set'] == forget_set_size]
        #     mean_scores = {'mean': np.mean(ul_data['score']), 'std': np.std(ul_data['score']), 'method': ul_approach, 'distinguiser':distinguisher_fp.parts[-1][:-4]}
        #     all_means.append(mean_scores)
        #     continue
        # else:
        #     ul_data = distinguisher_data[distinguisher_data['forget_set'] == ul_approach]
        #     greater_than = (ul_data['score'].values > control_data['score'].values).sum() / len(ul_data['score'].values)
        #     less_than = (ul_data['score'].values < control_data['score'].values).sum() / len(ul_data['score'].values)
        #     advantage = (max(greater_than, less_than)- 0.5) * 2
        #     row_data = {
        #         'distinguisher': distinguisher_name,
        #         'advantage': advantage,
        #         'unlearning': ul_approach
        #     }
        #     # print(greater_than, less_than)
        #     graph_data.append(row_data)
        #     mean_scores = {'mean': np.mean(ul_data['score']), 'std': np.std(ul_data['score']), 'method': ul_approach, 'distinguiser':distinguisher_fp.parts[-1][:-4]}
        #     all_means.append(mean_scores)
graph_df = pd.DataFrame.from_dict(graph_data)
adv_data = pd.DataFrame.from_dict(adv_data)

In [36]:
adv_data

,distinguisher,advantage,forget_set_size,win_percentage,model,clean_accuracy,poison_accuracy,poison_tpr,swap_test_score
0,kld,1.0,0.1,1.0,Amnesiac,0.796933,0.000333,0.0,0.978700
1,kld,1.0,0.1,1.0,Bad Teacher,0.810067,0.007133,0.0,0.998233
2,kld,1.0,0.1,1.0,Gradient Ascent,0.143000,0.000000,0.0,0.999867
3,kld,1.0,0.1,1.0,SCRUB,0.234733,0.000000,0.0,0.987233
4,kld,1.0,0.1,1.0,SSD,0.831067,0.999733,0.0,0.997933
5,mia,1.0,0.1,1.0,Amnesiac,0.796933,0.000333,0.0,0.978700
6,mia,1.0,0.1,1.0,Bad Teacher,0.810067,0.007133,0.0,0.998233
7,mia,1.0,0.1,1.0,Gradient Ascent,0.143000,0.000000,0.0,0.999867
8,mia,1.0,0.1,1.0,SCRUB,0.234733,0.000000,0.0,0.987233
9,mia,1.0,0.1,1.0,SSD,0.831067,0.999733,0.0,0.997933
10,mse,1.0,0.1,1.0,Amnesiac,0.796933,0.000333,0.0,0.978700
11,mse,1.0,0.1,1.0,Bad Teacher,0.810067,0.007133,0.0,0.998233
12,mse,1.0,0.1,1.0,Gradient Ascent,0.143000,0.000000,0.0,0.999867
13,mse,1.0,0.1,1.0,SCRUB,0.234733,0.000000,0.0,0.987233
14,mse,1.0,0.1,1.0,SSD,0.831067,0.999733,0.0,0.997933